name: blue-gitops
on:
  push:
    branches: ['env-*']
  delete:
    branches: ['env-*']

jobs:
  build-and-deploy-environment:
    if: github.event_name == 'push' && contains('refs/heads/env-', github.ref)
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        run: cd .blue/infra && ./blue up myapp ${GITHUB_REF##*/env-}
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  delete-environment:
    if: github.event_name == 'delete' && contains('refs/heads/env-', github.ref)
    runs-on: ubuntu-latest
    steps:
      - name: Delete environment
        run: cd .blue/infra && ./blue down myapp ${GITHUB_REF##*/env-}
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

