name: blue-gitops
on:
  push:
    branches: ['env-*']
  delete:
    branches: ['env-*']

jobs:
  build-and-deploy-environment:
    if: github.event_name == 'push' && contains(github.ref, 'refs/heads/env-')
    runs-on: ubuntu-latest
    steps:
      # - name: Build docker image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .devcontainer
      #     push: false
      #     tags: blue:latest
      # - uses: addnab/docker-run-action@v3
      #   with:
      #     image: blue:latest
      #     shell: bash
      #     options: -v ${{ github.workspace }}:/work -e AZURE_CREDENTIALS=${AZURE_CREDENTIALS} -e GITHUB_REF=${GITHUB_REF}
      #     run: cd /work/.blue/infra && ./blue up myapp ${GITHUB_REF##*/env-}
      #   env:
      #     AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Prepare environment
        run: cd .blue/infra && ./blue.sh up myapp ${GITHUB_REF##*/env-}
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  delete-environment:
    if: github.event_name == 'delete' && contains(github.ref, 'refs/heads/env-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete environment
        run: cd .blue/infra && ./blue.sh down myapp ${GITHUB_REF##*/env-}
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

